add branch header
bogatyrms/project-majesticteam05 pull request #6
Opened 2024-06-27 17:09 UTC by LidaDruzyak

2024-06-28 13:21 UTC, bogatyrms requested changes
Чекаю на оновлення.

2024-06-28 18:41 UTC, LidaDruzyak commented
на 80% готово

2024-06-29 08:07 UTC, bogatyrms requested changes
У десктопній версії під хедером відсутня тінь, поточна сторінка (синій кружок) не відображається, відстань між contact us та соц мережами повинна бути 203 px, а у вас вона менша.
У планшетній версії, меню повинно бути з правої сторони, список (home, about us, catalog і тд) повинен бути відцентрований по горизонталі, іконки у меню трохи змістились вниз.
У мобільній версії у меню треба прибрати зайву відстань, додати паддінги, і замінити колір фону на #FBFBFB

2024-06-29 13:43 UTC, LidaDruzyak commented
начебто все)

2024-06-30 16:06 UTC, bogatyrms approved these changes

2024-06-30 16:12 UTC, merged